package uk.gov.digital.ho.proving.income.api;

public enum FinancialCheckValues {
    NON_CONSECUTIVE_MONTHS,
    MONTHLY_VALUE_BELOW_THRESHOLD,
    MONTHLY_SALARIED_PASSED,
    NOT_ENOUGH_RECORDS,
    WEEKLY_SALARIED_PASSED,
    WEEKLY_VALUE_BELOW_THRESHOLD
}
